export const filterData: any = {
  'ethereum-phunks': {
    sex: ['female', 'male', 'zombie', 'ape', 'alien'],
    ears: ['earring'],
    eyes: [
      'green-eye-shadow',
      'nerd-glasses',
      'big-shades',
      'purple-eye-shadow',
      'clown-eyes-blue',
      'blue-eye-shadow',
      'clown-eyes-green',
      'regular-shades',
      'small-shades',
      'eye-mask',
      'horned-rim-glasses',
      'classic-shades',
      'vr',
      'eye-patch',
      '3d-glasses',
      'welding-goggles',
    ],
    hair: [
      'blonde-bob',
      'mohawk',
      'wild-hair',
      'half-shaved',
      'do-rag',
      'wild-white-hair',
      'messy-hair',
      'police-cap',
      'straight-hair-dark',
      'blonde-short',
      'straight-hair-blonde',
      'pilot-helmet',
      'stringy-hair',
      'bandana',
      'crazy-hair',
      'mohawk-dark',
      'dark-hair',
      'peak-spike',
      'cap',
      'frumpy-hair',
      'red-mohawk',
      'shaved-head',
      'knitted-cap',
      'fedora',
      'straight-hair',
      'hoodie',
      'headband',
      'cowboy-hat',
      'tassle-hat',
      'pink-with-hat',
      'vampire-hair',
      'mohawk-thin',
      'tiara',
      'cap-forward',
      'purple-hair',
      'beanie',
      'clown-hair-green',
      'pigtails',
      'orange-side',
      'wild-blonde',
      'top-hat',
    ],
    emotion: ['smile', 'frown'],
    mouth: ['pipe', 'cigarette', 'vape', 'medical-mask'],
    beard: [
      'goat',
      'luxurious-beard',
      'big-beard',
      'muttonchops',
      'handlebars',
      'normal-beard-black',
      'normal-beard',
      'chinstrap',
      'shadow-beard',
      'mustache',
      'front-beard-dark',
      'front-beard',
    ],
    face: ['spots', 'mole'],
    nose: ['clown-nose'],
    lips: ['black-lipstick', 'purple-lipstick', 'hot-lipstick'],
    neck: ['choker', 'gold-chain', 'silver-chain'],
    cheeks: ['rosy-cheeks'],
    teeth: ['buck-teeth'],
  },
  'missing-phunks': {
    sex: ['alien', 'ape', 'zombie', 'male', 'female'],
    ears: ['earring', 'earrings'],
    hair: [
      'messy-hair',
      'headband',
      'purple-hair',
      'beanie',
      'hoodie',
      'fedora',
      'top-hat',
      'cowboy-hat',
      'do-rag',
      'stringy-hair',
      'clown-hair-green',
      'police-cap',
      'crazy-hair',
      'bandana',
      'front-beard-dark',
      'knitted-cap',
      'cap',
      'wild-hair',
      'mohawk-dark',
      'cap-forward',
      'shaved-head',
      'mohawk-thin',
      'vampire-hair',
      'green-clown-hair',
      'mohawk',
      'orange-side',
      'wild-blonde',
      'tiara',
      'pigtails',
      'pilot-helmet',
      'straight-hair-blonde',
      'half-shaved',
      'pink-with-hat',
      'blonde-bob',
      'wild-white-hair',
      'wild-blonde-hair',
      'blonde-short',
      'dark-hair',
      'tassle-hat',
    ],
    neck: ['gold-chain', 'choker', 'silver-chain'],
    teeth: ['buck-teeth'],
    eyes: [
      'regular-shades',
      'vr',
      '3d-glasses',
      'eye-patch',
      'eye-mask',
      'nerd-glasses',
      'big-shades',
      'clown-eyes-blue',
      'clown-eyes-green',
      'blue-eye-shadow',
      'purple-eye-shadow',
      'green-eye-shadow',
      'welding-goggles',
    ],
    emotion: ['smile', 'frown'],
    beard: [
      'big-beard',
      'normal-beard',
      'shadow-beard',
      'luxurious-beard',
      'mustache',
      'front-beard-dark',
      'front-beard',
      'normal-black-beard',
      'muttonchops',
      'normal-beard-black',
      'handlebars',
      'hnadlebars',
      'frond-beard-dark',
      'chinstrap',
    ],
    nose: ['clown-nose'],
    mustache: ['handlebars'],
    face: ['spots', 'mole'],
    cheeks: ['rosy-cheeks'],
    lips: ['black-lipstick', 'purple-lipstick', 'hot-lipstick'],
  },
  'misprint-mingos': {
    '1-of-1': ['genesis', 'test', 'glitch_bitch'],
    'hat/helmet': [
      'backwards-cap-black',
      'backwards-cap-white',
      'backwards-cap-blue',
      'backwards-cap-red',
      'baseball-cap-black',
      'fb-helmet-red',
      'knit-orange',
      'backwards-cap-olive',
      'bucket-hat-purple',
      'space-helmet',
      'knit-royal',
      'bucket-hat-white',
      'bucket-hat-teal',
      'knight-helmet',
      'knit-white',
      'fb-helmet-green',
      'knit-yellow',
      'baseball-cap-white',
      'cowboy',
      'knit-purple',
      'baseball-cap-navy',
      'racer-red',
      'lumberjack-hat',
      'backwards-cap-purple',
      'fb-helmet-blue',
      'backwards-cap-fly',
      'top-hat',
      'racer-orange',
      'baseball-cap-purple',
      'fb-helmet-olive',
      'fb-helmet-orange',
      'energy-dome-2004',
      'coonskin-cap',
      'racer-yellow',
      'll-bucket',
      'backwards-cap-leather',
      'spartan-helmet',
    ],
    'shirt/jacket': [
      'long-sleeve-white',
      'hoodie',
      'hawaiian',
      'puffy-coat-blue',
      'tie-dye',
      'dojo-top',
      'work-jacket',
      'french-navy-sweater',
      'blocky-sweater',
      'lumberjack-flannel',
      'dress-shirt-pink',
      'puffy-coat-yellow',
      'moto-jacket-yellow',
      'dress-shirt-blue',
      'blue-flannel',
      'puffy-coat-orange',
      'dress-shirt-white',
      'spacesuit',
      'football---megatron',
      'long-sleeve-deep-v',
      'breakdancer-elite',
      'pajamas',
      'long-sleeve-grey',
      'long-sleeve-v-blue',
      'satin-gold-jacket',
      'long-sleeve-v-red',
      'camo-jacket',
      'long-sleeve-v-aqua',
      'varsity-purple',
      'long-sleeve-v-pink',
      'tux',
      'faux-shearling',
      'puffy-coat-green',
      'cool-g-sweater',
      'tubesock---lakers',
      'tubesock---hawks',
      'puffy-coat-pink',
      'long-sleeve-natural',
      'breakdancer-blue',
      'bathrobe',
      'tennis-sweater',
      'mingoneck-aqua',
      'toga',
      'desert-camo',
      'ribbed-sweater',
      'breakdancer-double-red',
      'football---bonk',
      'football---duke',
      'football---cheese-head',
      'moto-jacket-black',
      'breakdancer-dmc',
      'vintage-track-jacket',
      'mingoneck-white',
      'puffy-coat-red',
      'moto-jacket-red',
      "tubesock---'murica",
      'jersey---sammy-d',
      'football---kneel',
      'varsity-blue',
      'football---island',
      'long-sleeve-olive',
      'cobra-top',
      'scrubs',
      'faux-fur',
      'bobsled-jacket',
      'tubesock---cavaliers',
      'bill-jacket',
      'football---sheriff',
      'argyle-sweater',
      'long-sleeve-pink',
      'varsity-burgundy',
      'big-small-sweater',
      'mingoneck-black',
      'faux-diplomat',
      'hef-robe',
      'fancy-flannel',
      'breakdancer-ll',
      'varsity-green',
      'granddad-sweater',
      'bball---trust',
      'racing-jacket',
      'bball---z',
    ],
    cape: ['royal-red', 'superhero', 'royal-purple'],
    type: [
      'mingo-boba',
      'mingo-barbie',
      'mingo-shrimp',
      'mingo-mollusk',
      'mingo-gruff',
      'invisimingo',
      'mingo-crab',
      'robomingo',
      'salamander',
      'stork',
      'alligator',
      'jet-head',
    ],
    glasses: [
      '3d-glasses',
      'vr-red',
      'noggles',
      'pit-vipers',
      'nerd-glasses',
      'vr-blue',
      'havana-shades',
      'purp-nerd',
      'eye-mask',
      'classic-shades',
    ],
    chain: ['gold', 'medallion'],
    background: [
      'gruff',
      'moon',
      'this-is-fine',
      'null',
      'cc0-sunset',
      'scribe',
      'purps',
      'havana',
      'punk',
      'nerd',
      'lava',
      'win95',
      'heli',
      'burrr',
    ],
    headband: ['dojo', 'blue', 'green', 'purple', 'gold', 'cobra', 'rude'],
    hair: [
      'shaggy',
      'long-black',
      'long-blonde',
      'flat-top',
      'frump',
      'long-pink',
      'afro',
      'long-ginger',
      'ponytail',
      'karen-cut',
      'white-shag',
      'dreads-short',
      'dreads-long',
    ],
    facial: ['solid-beard', 'epic-beard', 'rainbow-vomit', 'shadow-beard'],
    smoke: ['cig', 'pipe'],
    mouth: ['beak-gold'],
    headphones: ['black', 'blue', 'gaming-headset', 'red', 'purple'],
    'ninja-outfit': ['midnight'],
    tie: ['blue', 'checkered', 'purple'],
    'vest/armor': [
      'knight-armor',
      'burrr-scarf',
      'life-vest',
      'safety-vest',
      'vc-vest',
      'lifesaver',
    ],
    mask: ['wrestler-green'],
  },
  'dysto-phunks': {
    sex: ['alien', 'ape', 'zombie', 'robot', 'male', 'female'],
    hair: [
      'cyber-brain',
      'hoodie',
      'mohawk-green',
      'short-mohawk',
      'thin-mohawk-green',
      'shadow-hoodie',
      'cap',
      'bandana',
      'knitted-cap',
      'brain-with-flies',
      'crazy-hair',
      'peak-spike',
      'police-cap',
      'brain-tube',
      'clown-hair-white',
      'undercut',
      'green-helmet',
      'flat-top-green',
      'infinity-shades-helmet',
      'invisible-helmet',
      'pompadour',
      'black-hair',
      'wild-green',
      'diamond-helmet',
      'short-black',
      'cap-forward',
      'pink-rose-hair',
      'exotic-black',
      'tiara',
      'purple-line',
      'straight-white',
      'pigtails-white',
      'welding-googles',
      'wild-black',
      'afro-hair',
      'green-side',
      'straight-black-hair',
      'purple-bob',
      'black-shaved',
      'messy-green',
      'wild-white',
    ],
    type: ['cyborg', 'philip', 'phunkbotv2', 'cyber-residents'],
    eyes: [
      'cyber-eye',
      'green-scouter',
      'holo-lens',
      'bionic-eye-patch',
      'cyclops-visor',
      'wide-shades',
      'neon-gaze',
      'hyper-zoom-vr',
      'meta-vr',
      'vr-headset',
      'vr-goggles',
      'point-glasses',
      'cyber-matrix',
      'wider-gaze',
      'cyber-sight',
      'void-goggles',
      'swamp-sight',
      'futuristic-shades',
      '3d-glasses',
      'wider-shades',
      'futuristic-ar',
      'ar-shades',
      'vr-goggles-flip',
      'classic-shades',
      'black-vr',
    ],
    mouth: [
      'shadow-synth-mask',
      'gas-mask',
      'metal-green-mask',
      'vape',
      'vortex-mask',
      'void-mask',
      'holo-black-mask',
      'neon-green-mask',
      'white-mustache',
      'black-mask',
      'green-alighment-mask',
      'undead-mask',
      'outlaw-mask',
      'eclipse-mask',
      'specter-shield-mask',
      'face-mask',
    ],
    neck: ['gold-chain', 'green-cover', 'black-cover'],
    ears: ['earring'],
  },
};

export const rarityData: any = {
  'ethereum-phunks': {
    Female: 3840,
    Earring: 2459,
    'Green Eye Shadow': 271,
    'Blonde Bob': 147,
    Male: 6039,
    Smile: 238,
    Mohawk: 441,
    'Wild Hair': 447,
    Pipe: 317,
    'Nerd Glasses': 572,
    Goat: 295,
    'Big Shades': 535,
    'Purple Eye Shadow': 262,
    'Half Shaved': 147,
    'Do-rag': 300,
    'Clown Eyes Blue': 384,
    Spots: 124,
    'Wild White Hair': 136,
    'Messy Hair': 460,
    'Luxurious Beard': 286,
    'Big Beard': 146,
    'Clown Nose': 212,
    'Police Cap': 203,
    'Blue Eye Shadow': 266,
    'Straight Hair Dark': 148,
    'Black Lipstick': 617,
    'Clown Eyes Green': 382,
    'Purple Lipstick': 655,
    'Blonde Short': 129,
    'Straight Hair Blonde': 144,
    'Pilot Helmet': 54,
    'Hot Lipstick': 696,
    'Regular Shades': 527,
    'Stringy Hair': 463,
    'Small Shades': 378,
    Frown: 261,
    'Eye Mask': 293,
    Muttonchops: 303,
    Bandana: 481,
    'Horned Rim Glasses': 535,
    'Crazy Hair': 414,
    'Classic Shades': 502,
    Handlebars: 263,
    'Mohawk Dark': 429,
    'Dark Hair': 157,
    'Peak Spike': 303,
    'Normal Beard Black': 289,
    Cap: 351,
    VR: 332,
    'Frumpy Hair': 442,
    Cigarette: 961,
    'Normal Beard': 292,
    'Red Mohawk': 147,
    'Shaved Head': 300,
    Chinstrap: 282,
    Mole: 644,
    'Knitted Cap': 419,
    Fedora: 186,
    'Shadow Beard': 526,
    'Straight Hair': 151,
    Hoodie: 259,
    'Eye Patch': 461,
    Headband: 406,
    'Cowboy Hat': 142,
    'Tassle Hat': 178,
    '3D Glasses': 286,
    Mustache: 288,
    Vape: 272,
    Choker: 48,
    'Pink With Hat': 95,
    'Welding Goggles': 86,
    'Vampire Hair': 147,
    'Mohawk Thin': 441,
    Tiara: 55,
    Zombie: 88,
    'Front Beard Dark': 260,
    'Cap Forward': 254,
    'Gold Chain': 169,
    'Purple Hair': 165,
    Beanie: 44,
    'Clown Hair Green': 148,
    Pigtails: 94,
    'Silver Chain': 156,
    'Front Beard': 273,
    'Rosy Cheeks': 128,
    'Orange Side': 68,
    'Wild Blonde': 144,
    'Buck Teeth': 78,
    'Top Hat': 115,
    'Medical Mask': 175,
    Ape: 24,
    Alien: 9,
  },
  'missing-phunks': {
    Alien: 12,
    Earring: 111,
    'Messy Hair': 14,
    'Gold Chain': 99,
    'Buck Teeth': 60,
    Headband: 26,
    'Purple Hair': 47,
    'Regular Shades': 26,
    Beanie: 20,
    Hoodie: 12,
    Fedora: 10,
    Smile: 27,
    'Big Beard': 22,
    'Top Hat': 15,
    Vr: 53,
    'Cowboy Hat': 33,
    '3d Glasses': 38,
    'Do-rag': 7,
    'Stringy Hair': 36,
    'Normal Beard': 13,
    'Clown Nose': 19,
    'Clown Hair Green': 26,
    'Shadow Beard': 33,
    Ape: 24,
    'Police Cap': 10,
    'Eye Patch': 14,
    'Luxurious Beard': 16,
    'Crazy Hair': 12,
    Bandana: 26,
    'Front Beard Dark': 10,
    'Eye Mask': 29,
    'Knitted Cap': 13,
    Mustache: 53,
    'Nerd Glasses': 4,
    'Front Beard': 5,
    Cap: 21,
    'Wild Hair': 9,
    'Big Shades': 7,
    Zombie: 36,
    Frown: 3,
    'Mohawk Dark': 1,
    'Cap Forward': 5,
    'Shaved Head': 9,
    'Normal Black Beard': 1,
    Muttonchops: 4,
    'Normal Beard Black': 6,
    'Mohawk Thin': 2,
    Handlebars: 10,
    'Vampire Hair': 2,
    Earrings: 1,
    Hnadlebars: 1,
    Male: 126,
    'Green Clown Hair': 1,
    Spots: 32,
    'Frond Beard Dark': 1,
    Mohawk: 2,
    Chinstrap: 6,
    'Clown Eyes Blue': 4,
    'Rosy Cheeks': 24,
    'Clown Eyes Green': 5,
    Mole: 1,
    Female: 51,
    'Orange Side': 10,
    'Black Lipstick': 9,
    'Wild Blonde': 4,
    Tiara: 9,
    'Purple Lipstick': 20,
    Pigtails: 7,
    'Pilot Helmet': 5,
    'Blue Eye Shadow': 4,
    'Straight Hair Blonde': 2,
    'Hot Lipstick': 19,
    'Purple Eye Shadow': 9,
    'Half Shaved': 5,
    'Green Eye Shadow': 6,
    'Pink With Hat': 2,
    Choker: 6,
    'Blonde Bob': 3,
    'Wild White Hair': 6,
    'Welding Goggles': 4,
    'Silver Chain': 4,
    'Wild Blonde Hair': 1,
    'Blonde Short': 1,
    'Dark Hair': 3,
    'Tassle Hat': 1,
  },
  'misprint-mingos': {
    Genesis: 1,
    'Backwards Cap Black': 145,
    'Long Sleeve White': 96,
    'Royal Red': 2,
    'Mingo Boba': 2,
    Test: 1,
    '3D Glasses': 95,
    Hoodie: 28,
    Gold: 118,
    'Mingo Barbie': 592,
    Hawaiian: 103,
    'Mingo Shrimp': 1597,
    'Puffy Coat Blue': 97,
    'Mingo Mollusk': 868,
    'Tie-Dye': 94,
    Gruff: 45,
    'Dojo Top': 26,
    'Backwards Cap White': 178,
    'Work Jacket': 41,
    'Mingo Gruff': 296,
    'French Navy Sweater': 85,
    'Backwards Cap Blue': 162,
    'Blocky Sweater': 28,
    'Lumberjack Flannel': 55,
    'Backwards Cap Red': 181,
    'Dress Shirt Pink': 65,
    'Puffy Coat Yellow': 46,
    'Moto Jacket Yellow': 83,
    'Baseball Cap Black': 122,
    'Dress Shirt Blue': 130,
    'Blue Flannel': 97,
    Moon: 25,
    Dojo: 15,
    Shaggy: 140,
    'Long Black': 160,
    'Long Blonde': 105,
    'Puffy Coat Orange': 66,
    'Solid Beard': 89,
    'Dress Shirt White': 131,
    Invisimingo: 139,
    'Mingo Crab': 162,
    'Epic Beard': 40,
    Spacesuit: 63,
    'FB Helmet Red': 14,
    'This Is Fine': 39,
    'Football - Megatron': 46,
    'Long Sleeve Deep V': 49,
    Cig: 106,
    'Breakdancer Elite': 60,
    Pajamas: 77,
    'Long Sleeve Grey': 37,
    'Long Sleeve V Blue': 37,
    Null: 133,
    'Knit Orange': 18,
    'Beak Gold': 36,
    'Flat Top': 75,
    'Satin Gold Jacket': 21,
    'Long Sleeve V Red': 72,
    'Camo Jacket': 57,
    'Long Sleeve V Aqua': 82,
    Robomingo: 19,
    'Varsity Purple': 41,
    'VR Red': 57,
    'Long Sleeve V Pink': 74,
    Tux: 25,
    'Backwards Cap Olive': 62,
    'Faux Shearling': 24,
    'Puffy Coat Green': 83,
    Black: 42,
    'Cool G Sweater': 18,
    'Tubesock - Lakers': 4,
    Superhero: 7,
    Noggles: 19,
    'Tubesock - Hawks': 21,
    'Puffy Coat Pink': 18,
    'Long Sleeve Natural': 46,
    'Pit Vipers': 6,
    'Breakdancer Blue': 82,
    'cc0 Sunset': 42,
    Frump: 47,
    'Long Pink': 20,
    Afro: 120,
    Bathrobe: 87,
    'Tennis Sweater': 40,
    Blue: 72,
    Salamander: 39,
    'Long Ginger': 40,
    'Mingoneck Aqua': 43,
    Toga: 26,
    'Gaming Headset': 124,
    Scribe: 17,
    'Nerd Glasses': 74,
    'Desert Camo': 43,
    'Ribbed Sweater': 43,
    'Breakdancer Double Red': 42,
    'Football - Bonk': 14,
    'VR Blue': 28,
    'Football - Duke': 31,
    'Football - Cheese Head': 24,
    'Moto Jacket Black': 50,
    'Breakdancer DMC': 15,
    'Vintage Track Jacket': 42,
    'Rainbow Vomit': 19,
    'Mingoneck White': 60,
    Stork: 5,
    Midnight: 2,
    'Puffy Coat Red': 70,
    'Havana Shades': 109,
    'Bucket Hat Purple': 15,
    'Space Helmet': 16,
    'Moto Jacket Red': 28,
    Pipe: 19,
    "Tubesock - 'Murica": 8,
    'Knit Royal': 35,
    'Jersey - Sammy D': 44,
    'Football - Kneel': 42,
    'Purp Nerd': 96,
    'Bucket Hat White': 35,
    Green: 17,
    'Varsity Blue': 57,
    'Football - Island': 33,
    'Long Sleeve Olive': 32,
    'Cobra Top': 21,
    'Bucket Hat Teal': 7,
    Scrubs: 23,
    Purps: 40,
    Ponytail: 36,
    'Faux Fur': 27,
    'Karen Cut': 35,
    'Bobsled Jacket': 23,
    'Tubesock - Cavaliers': 21,
    Purple: 19,
    'Knight Helmet': 10,
    'Shadow Beard': 45,
    Glitch_Bitch: 1,
    Checkered: 2,
    'Bill Jacket': 23,
    'Knit White': 11,
    'Football - Sheriff': 11,
    Red: 15,
    'Argyle Sweater': 38,
    'White Shag': 28,
    'Long Sleeve Pink': 11,
    'Varsity Burgundy': 31,
    'Dreads Short': 27,
    'Knight Armor': 3,
    'FB Helmet Green': 12,
    'Big Small Sweater': 7,
    'Mingoneck Black': 14,
    'Faux Diplomat': 25,
    'Hef Robe': 25,
    'Fancy Flannel': 21,
    'Knit Yellow': 12,
    'Breakdancer LL': 8,
    Cobra: 3,
    Havana: 50,
    'Baseball Cap White': 9,
    Cowboy: 1,
    'Varsity Green': 30,
    'Knit Purple': 23,
    Punk: 28,
    'Baseball Cap Navy': 14,
    'Dreads Long': 43,
    'Burrr Scarf': 1,
    Alligator: 7,
    'Racer Red': 4,
    'Lumberjack Hat': 13,
    Nerd: 38,
    Medallion: 3,
    'Backwards Cap Purple': 19,
    'FB Helmet Blue': 8,
    'Backwards Cap Fly': 2,
    'Eye Mask': 8,
    'Granddad Sweater': 19,
    'Classic Shades': 4,
    'BBall - Trust': 1,
    'Top Hat': 1,
    'Racer Orange': 8,
    'Racing Jacket': 7,
    'Life Vest': 4,
    Rude: 2,
    'Baseball Cap Purple': 7,
    'FB Helmet Olive': 3,
    'Safety Vest': 1,
    'FB Helmet Orange': 5,
    'Energy Dome 2004': 1,
    'BBall - Z': 2,
    'Coonskin Cap': 1,
    'Racer Yellow': 2,
    'VC Vest': 2,
    Lifesaver: 1,
    'LL Bucket': 2,
    'Wrestler Green': 1,
    'Royal Purple': 2,
    'Backwards Cap Leather': 2,
    Lava: 4,
    Win95: 3,
    'Spartan Helmet': 1,
    Heli: 4,
    Burrr: 2,
    'Jet Head': 2,
  },
  'dysto-phunks': {
    Alien: 5,
    'Cyber Brain': 2,
    Cyborg: 9,
    Hoodie: 7,
    'Cyber Eye': 7,
    'Shadow Synth Mask': 6,
    'Mohawk Green': 3,
    'Gas Mask': 5,
    'Short Mohawk': 2,
    'Green Scouter': 7,
    'Metal Green Mask': 4,
    'Thin Mohawk Green': 4,
    'Holo Lens': 2,
    Vape: 5,
    'Gold Chain': 9,
    Ape: 7,
    'Bionic Eye Patch': 4,
    'Shadow Hoodie': 2,
    'Cyclops Visor': 5,
    Cap: 2,
    'Wide Shades': 1,
    'Neon Gaze': 4,
    Bandana: 2,
    'Vortex Mask': 3,
    'Knitted Cap': 1,
    Zombie: 9,
    'Brain With Flies': 3,
    'Void Mask': 3,
    'Crazy Hair': 2,
    'Hyper Zoom Vr': 1,
    Earring: 14,
    'Peak Spike': 3,
    'Holo Black Mask': 3,
    'Meta Vr': 2,
    Robot: 6,
    'Neon Green Mask': 3,
    'Vr Headset': 2,
    'Police Cap': 1,
    'Vr Goggles': 1,
    Male: 24,
    'Brain Tube': 1,
    'Clown Hair White': 1,
    'Point Glasses': 1,
    'White Mustache': 1,
    'Green Cover': 2,
    Undercut: 1,
    'Cyber Matrix': 1,
    'Black Mask': 1,
    'Green Helmet': 2,
    'Wider Gaze': 1,
    'Green Alighment Mask': 1,
    'Flat Top Green': 1,
    'Cyber Sight': 1,
    'Black Cover': 1,
    'Void Goggles': 1,
    'Undead Mask': 1,
    'Infinity Shades Helmet': 1,
    'Invisible Helmet': 1,
    'Swamp Sight': 1,
    'Outlaw Mask': 2,
    'Eclipse Mask': 2,
    Pompadour: 1,
    'Black Hair': 1,
    'Futuristic Shades': 1,
    'Specter Shield Mask': 2,
    'Wild Green': 1,
    '3d Glasses': 1,
    'Wider Shades': 1,
    'Face Mask': 2,
    'Futuristic AR': 1,
    'Diamond Helmet': 1,
    'AR Shades': 2,
    'Short Black': 1,
    Philip: 1,
    'Cap Forward': 1,
    'Vr Goggles Flip': 1,
    PhunkBotV2: 1,
    'Cyber Residents': 2,
    Female: 19,
    'Pink Rose Hair': 1,
    'Exotic Black': 1,
    Tiara: 3,
    'Purple Line': 1,
    'Straight White': 1,
    'Pigtails White': 1,
    'Welding Googles': 1,
    'Wild Black': 1,
    'Afro Hair': 1,
    'Green Side': 2,
    'Straight Black Hair': 1,
    'Purple Bob': 1,
    'Black Shaved': 2,
    'Messy Green': 1,
    'Classic Shades': 2,
    'Wild White': 1,
    'Black Vr': 1,
  },
};
